### ISSUE TITLE
InvalidTypeNameException[mapping type name [_taste] can't start with '_']

### ISSUE THREAD

**Issue by eliasah** [codelibs/elasticsearch-taste#23]
Hello,

I'm trying out the taste-plugin using Elasticsearch 1.1.1 and thus the version 0.1 of the plugin.

Using the sample code in home README.md file after download the u.data file.

```
cat u.data | awk '{system("curl -XPOST localhost:9200/movielens/_taste/event?pretty -d \"{\\\"user\\\":{\\\"id\\\":" $1 "},\\\"item\\\":{\\\"id\\\":" $2 "},\\\"value\\\":" $3 ",\\\"timestamp\\\":" $4 "000}\"")}'
```

I get the following error.

```
{
  "error" : "InvalidTypeNameException[mapping type name [_taste] can't start with '_']",
  "status" : 400
}
```

Can anyone please give me an explanation on what's happening?

**Comment by muraree** [comment]
Hello,

I am facing same issue with Elasticsearch 1.4.2 and elasticsearch-taste 1.5.0

please see error log:

[2015-06-10 17:38:57,928][DEBUG][action.index             ] [Claudette St. Croix] [movielens][1], node[jm674UFtQIqnyJVPze0nDg], [P], s[STARTED]: Failed to execute [index {[movielens][_taste][event], source[{"user":{"id":244},"item":{"id":51},"value":2,"timestamp":880606923000}]}]
org.elasticsearch.indices.InvalidTypeNameException: mapping type name [_taste] can't start with '_'
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:329)
	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:317)
	at org.elasticsearch.index.mapper.MapperService.documentMapperWithAutoCreate(MapperService.java:477)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:412)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:189)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:511)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
