### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by cyanglee** [codelibs/elasticsearch-taste#27]
Hi, 

I ran into some problems installing this plugin and wonder if anyone could help.

Env: OSX 10.10.1
Elasticsearch version: 1.4.0 (installed through homebrew)

I installed the plugin by running the command provided in the doc:

```
plugin --install org.codelibs/elasticsearch-taste/0.4.0                                                                                                                                                           [ruby-2.1.0]
-> Installing org.codelibs/elasticsearch-taste/0.4.0...
Trying http://download.elasticsearch.org/org.codelibs/elasticsearch-taste/elasticsearch-taste-0.4.0.zip...
Trying http://search.maven.org/remotecontent?filepath=org/codelibs/elasticsearch-taste/0.4.0/elasticsearch-taste-0.4.0.zip...
Downloading........DONE
Installed org.codelibs/elasticsearch-taste/0.4.0 into /usr/local/var/lib/elasticsearch/plugins/taste
```

After restarting elasticsearch, I received the following error:

```
elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml                                                                                                                                      [ruby-2.1.0]
[2014-12-24 13:17:23,614][INFO ][node                     ] [Fagin] version[1.4.0], pid[21886], build[bc94bd8/2014-11-05T14:26:12Z]
[2014-12-24 13:17:23,615][INFO ][node                     ] [Fagin] initializing ...
[2014-12-24 13:17:23,625][WARN ][plugins                  ] [Fagin] failed to load plugin from [jar:file:/usr/local/var/lib/elasticsearch/plugins/taste/elasticsearch-taste-0.4.0.jar!/es-plugin.properties]
org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.codelibs.elasticsearch.taste.TastePlugin]
    at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:531)
    at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:406)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:115)
    at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:150)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
    at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:203)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.UnsupportedClassVersionError: org/codelibs/elasticsearch/taste/TastePlugin : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:508)
    ... 7 more
[2014-12-24 13:17:23,631][INFO ][plugins                  ] [Fagin] loaded [], sites []
[2014-12-24 13:17:25,937][INFO ][node                     ] [Fagin] initialized
[2014-12-24 13:17:25,937][INFO ][node                     ] [Fagin] starting ...
[2014-12-24 13:17:25,995][INFO ][transport                ] [Fagin] bound_address {inet[/127.0.0.1:9300]}, publish_address {inet[/127.0.0.1:9300]}
[2014-12-24 13:17:26,009][INFO ][discovery                ] [Fagin] elasticsearch_cyanglee/Rfa9ma4eROKuSNctfSqAAw
[2014-12-24 13:17:29,803][INFO ][cluster.service          ] [Fagin] new_master [Fagin][Rfa9ma4eROKuSNctfSqAAw][cyanglee.local][inet[/127.0.0.1:9300]], reason: zen-disco-join (elected_as_master)
[2014-12-24 13:17:29,821][INFO ][http                     ] [Fagin] bound_address {inet[/127.0.0.1:9200]}, publish_address {inet[/127.0.0.1:9200]}
[2014-12-24 13:17:29,821][INFO ][node                     ] [Fagin] started
[2014-12-24 13:17:30,269][INFO ][gateway                  ] [Fagin] recovered [2] indices into cluster_state
^C[2014-12-24 13:19:33,432][INFO ][node                     ] [Fagin] stopping ...
[2014-12-24 13:19:33,483][INFO ][node                     ] [Fagin] stopped
[2014-12-24 13:19:33,483][INFO ][node                     ] [Fagin] closing ...
[2014-12-24 13:19:33,486][INFO ][node                     ] [Fagin] closed
```

Any helps is appreciated. Thanks!

**Comment by muraree** [comment]
Hello, 
I am also facing same issue with elasticsearch(1.4.2)
Could any one can let me know what java version i need to required!

Any helps is appreciated. Thanks!

**Comment by cyanglee** [comment]
@muraree I am currently on java 1.8.0_25 and it works for me.

**Comment by muraree** [comment]
@cyanglee  Thanks for your response!
I installled java 8 but still getting same issue.. 

org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.codelibs.elasticsearch.taste.TastePlugin]

**Comment by marevol** [comment]
@muraree I do not think your elasticsearch runs on the installed java 8.
Please check  PATH and JAVA_HOME variable.

**Comment by muraree** [comment]
@marevol  I have checked PATH and JAVA_HOME variable.

$ echo $PATH
/home/rails/android-sdk-linux/tools:/home/rails/android-sdk-linux/platform-tools:/home/rails/android-sdk-linux/build-tools/19.1.0:/usr/local/heroku/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/rails/.rvm/bin:/home/rails/.rvm/bin:/home/rails/bin:/usr/lib/jvm/java-8-oracle/bin

$ echo $JAVA_HOME
/usr/lib/jvm/java-8-oracle

**Comment by marevol** [comment]
$ which java
$ ps aux | grep java

**Comment by muraree** [comment]
$ which java
/usr/bin/java

$  ps aux | grep java
120       2044  0.7  5.4 1269348 220852 ?      Sl   15:48   1:06 /usr/lib/jvm/java-7-oracle/bin/java -Xms256m -Xmx1g -Xss256k -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.pidfile=/var/run/elasticsearch.pid -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.4.2.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.default.config=/etc/elasticsearch/elasticsearch.yml -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.work=/tmp/elasticsearch -Des.default.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.Elasticsearch
rails     5726  0.0  0.0   4392   828 pts/2    S+   18:13   0:00 grep --color=auto java

**Comment by marevol** [comment]
The environment variable for the system is different from one for user.
You need to set proper variables to system's one(ex. change java version with alternative command).

**Comment by muraree** [comment]
Its working now :)
Thank you for help!
