### ISSUE TITLE
Plugin failure on ES 1.4.0

### ISSUE THREAD

**Issue by tgmweb** [codelibs/elasticsearch-taste#28]
When installing the plugin and restarting Elasticsearch, I get the following:

org.elasticsearch.ElasticsearchException: Failed to load plugin class [org.codelibs.elasticsearch.taste.TastePlugin]
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:531)
        at org.elasticsearch.plugins.PluginsService.loadPluginsFromClasspath(PluginsService.java:406)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:115)
        at org.elasticsearch.node.internal.InternalNode.<init>(InternalNode.java:150)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:159)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:70)
        at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:203)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Caused by: java.lang.UnsupportedClassVersionError: org/codelibs/elasticsearch/taste/TastePlugin : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:508)

**Comment by tgmweb** [comment]
I see there's a closed ticket with the same issue due to ambiguity of the readme.
