### ISSUE TITLE
SearchParseException: Parse Failure [No mapping found for [@timestamp] in order to sort on]

### ISSUE THREAD

**Issue by gponster** [codelibs/elasticsearch-taste#39]
I've installed elasticsearch-taste(1.6.0-SNAPSHOT) with elasticsearch(1.6.1)
When I run first step it's failed to create index
cat u.data | awk '{system("curl -XPOST localhost:9200/movielens/_taste/event?pretty -d \"{\\"user\\":{\\"id\\":" $1 "},\\"item\\":{\\"id\\":" $2 "},\\"value\\":" $3 ",\\"timestamp\\":" $4 "000}\"")}'

Here is the exception
Failed to execute [org.elasticsearch.action.search.SearchRequest@6e4a7280]
org.elasticsearch.search.SearchParseException: [movielens][4]: query[system_id:196],from[-1],size[1]: Parse Failure [Failed to parse source [{"size":1,"query":{"term":{"system_id":196}},"fields":"user_id","sort":[{"@timestamp":{"order":"desc"}}]}]]
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:747)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:572)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:544)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:306)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:231)
	at org.elasticsearch.search.action.SearchServiceTransportAction$5.call(SearchServiceTransportAction.java:228)
	at org.elasticsearch.search.action.SearchServiceTransportAction$23.run(SearchServiceTransportAction.java:559)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by fedeisas** [comment]
I'm getting the same error when I try to fetch recommendations :-(
